In [16]:
import pandas as pd

# Replace 'file.csv' with your CSV file's path
file_path = "/Users/akshaysapra/co2-emission-ML/src/data/agricultural-land.csv"

# Read the CSV file into a Pandas DataFrame
data = pd.read_csv(file_path)

refined_data = data [data ['Year']>=2000]

print(refined_data.head(20))
refined_data.shape
refined_data.to_csv('agricultural-land_2000to2020.csv',index=False)

         Entity Code  Year  \
39  Afghanistan  AFG  2000
40  Afghanistan  AFG  2001
41  Afghanistan  AFG  2002
42  Afghanistan  AFG  2003
43  Afghanistan  AFG  2004
44  Afghanistan  AFG  2005
45  Afghanistan  AFG  2006
46  Afghanistan  AFG  2007
47  Afghanistan  AFG  2008
48  Afghanistan  AFG  2009
49  Afghanistan  AFG  2010
50  Afghanistan  AFG  2011
51  Afghanistan  AFG  2012
52  Afghanistan  AFG  2013
53  Afghanistan  AFG  2014
54  Afghanistan  AFG  2015
55  Afghanistan  AFG  2016
56  Afghanistan  AFG  2017
57  Afghanistan  AFG  2018
58  Afghanistan  AFG  2019

    Agricultural land | 00006610 || Area | 005110 || hectares
39                                         37753000.0
40                                         37753000.0
41                                         37753000.0
42                                         37910000.0
43                                         37911000.0
44                                         37910000.0
45                                         37910000.0
46                                         37910000.0
47                                         37910000.0
48                                         37910000.0
49                                         37911000.0
50                                         37910000.0
51                                         37910000.0
52                                         37910000.0
53                                         37910000.0
54                                         37910000.0
55                                         37910000.0
56                                         37910000.0
57                                         38010000.0
58                                         38010000.0

In [18]:
# Load the CSV data into a DataFrame
csv_file = 'country_CO2_and_energy_2000to2018.csv'
csv_data = pd.read_csv(csv_file)

# Assuming 'refined_data' is your DataFrame
# Perform the merge based on 'Entity' and 'Year' with 'country' and 'year'
merged_data = pd.merge(refined_data, csv_data, left_on=['Entity', 'Year'], right_on=['country', 'year'], how='inner')

# Now 'merged_data' contains the merged information
# You can perform further operations or analysis on this merged DataFrame
merged_data

,Entity,Code,Year,Agricultural land | 00006610 || Area | 005110 || hectares,country,year,iso_code,population,gdp,cement_co2,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,Afghanistan,AFG,2000,37753000.0,Afghanistan,2000,AFG,19542986.0,1.128379e+10,0.010,...,0.000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
1,Afghanistan,AFG,2001,37753000.0,Afghanistan,2001,AFG,19688634.0,1.102127e+10,0.007,...,0.000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
2,Afghanistan,AFG,2002,37753000.0,Afghanistan,2002,AFG,21000258.0,1.880487e+10,0.011,...,0.000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
3,Afghanistan,AFG,2003,37910000.0,Afghanistan,2003,AFG,22645136.0,2.107434e+10,0.010,...,0.000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
4,Afghanistan,AFG,2004,37911000.0,Afghanistan,2004,AFG,23553554.0,2.233257e+10,0.010,...,0.000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3055,Zimbabwe,ZWE,2014,16200000.0,Zimbabwe,2014,ZWE,13855758.0,2.122250e+10,0.496,...,0.000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
3056,Zimbabwe,ZWE,2015,16200000.0,Zimbabwe,2015,ZWE,14154937.0,2.102745e+10,0.585,...,0.106,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
3057,Zimbabwe,ZWE,2016,16200000.0,Zimbabwe,2016,ZWE,14452705.0,2.096179e+10,0.461,...,0.147,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
3058,Zimbabwe,ZWE,2017,16200000.0,Zimbabwe,2017,ZWE,14751101.0,2.194784e+10,0.469,...,0.136,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
3059,Zimbabwe,ZWE,2018,16200000.0,Zimbabwe,2018,ZWE,15052191.0,2.271535e+10,0.558,...,0.218,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN

In [19]:
merged_data.to_csv('merged_data.csv',index=False)