In [2]:
import pandas as pd
import sys
sys.path.append('..')  # Move one level up in the directory structure
from src.data.get_dataset import get_merged_datasets, get_merged_code_books

merged_df = get_merged_datasets()
merged_df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,Afghanistan,1900,AFG,4707744.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1901,AFG,4751177.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1902,AFG,4802500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1903,AFG,4861833.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1904,AFG,4921891.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232538,Zimbabwe,2017,ZWE,14751101.0,2.194784e+10,0.469,0.032,9.596,-0.937,-8.899,...,0.136,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
232539,Zimbabwe,2018,ZWE,15052191.0,2.271535e+10,0.558,0.037,11.795,2.199,22.920,...,0.218,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
232540,Zimbabwe,2019,ZWE,15354606.0,NaN,0.570,0.037,11.115,-0.681,-5.772,...,0.364,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
232541,Zimbabwe,2020,ZWE,15669663.0,NaN,0.570,0.036,10.608,-0.507,-4.559,...,0.395,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
232542,Zimbabwe,2021,ZWE,15993525.0,NaN,0.570,0.036,11.296,0.688,6.488,...,0.498,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN

In [6]:



file_path = "/Users/akshaysapra/co2-emission-ML/src/data/Time Series - GHGs from Agriculture, in kt COâ‚‚ equivalent.xlsx"

data = pd.read_excel(file_path)

print(data.head())

  Time Series - GHGs from Agriculture, in kt COâ‚‚ equivalent    Unnamed: 1  \
0                                                NaN                  NaN
1                                              Party            Base year
2                                          Australia         84926.981856
3                                            Austria          8399.709224
4                                            Belarus         29869.317438

     Unnamed: 2    Unnamed: 3    Unnamed: 4    Unnamed: 5    Unnamed: 6  \
0           NaN           NaN           NaN           NaN           NaN
1          1990          1991          1992          1993          1994
2  84926.981856  84131.039797  81404.155876  79409.420148  79465.416064
3   8399.709224   8310.599653   7968.442515   8073.152598   8035.802719
4  29869.317438  28454.454074   25542.52278  24742.298984   21373.14641

     Unnamed: 7    Unnamed: 8    Unnamed: 9  ...   Unnamed: 25   Unnamed: 26  \
0           NaN           NaN           NaN  ...           NaN           NaN
1          1995          1996          1997  ...          2013          2014
2  75915.225639  78100.892772  79320.664614  ...   75966.97196  76429.616062
3   8130.441884   7994.766465   7935.839534  ...   7211.166679   7346.220919
4  20134.784531  20079.545647  20484.073475  ...  21168.246487     20654.612

    Unnamed: 27   Unnamed: 28   Unnamed: 29   Unnamed: 30   Unnamed: 31  \
0           NaN           NaN           NaN           NaN           NaN
1          2015          2016          2017          2018          2019
2  73559.271161  72639.837213  76552.451452  75148.799587  69752.774176
3   7375.995656   7488.818927   7444.131993   7330.204602   7221.212408
4   20473.14549  20550.692187  20941.175195  20625.071553  20550.406837

    Unnamed: 32                 Unnamed: 33  \
0           NaN                         NaN
1          2020  Last Inventory Year (2021)
2  67830.808838                           â€”
3   7197.456035                 7221.163423
4  21139.734176                21178.889083

                                     Unnamed: 34
0                                            NaN
1  Change from base year to latest reported year
2                                             -1
3                                      -0.140308
4                                      -0.290948

[5 rows x 35 columns]

In [3]:
pwd

'/Users/akshaysapra/co2-emission-ML/notebooks'